name: PHP Composer

on:
  push:
#    branches: [ "master" ] # removed when testing tac branch
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read


strategy:
  matrix:
    php-version:
      - '8.3'
      - '8.4'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: shivammathur/setup-php@v2

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      with:
        php: 8.3
      run: composer install --prefer-dist --no-progress

    - name: Run test suite
      with:
        php: 8.3
      run: php ./vendor/bin/phpunit

    - name: Run cs fixer
      run: php ./vendor/bin/php-cs-fixer fix --config=.php_cs.php --verbose --diff --dry-run --allow-risky=yes
